Style/ClassVars:
  Enabled: false

Style/GlobalVars:
  AllowedVariables:
    - $gtk
    - $args
    - $state
    - $clipboard

Style/NumericPredicate:
  EnforcedStyle: comparison

Naming/MethodParameterName:
  AllowedNames:
    - x
    - 'y'
    - w
    - h
    - rt

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false
